/**
 * Star Citizen action display names.
 * Auto-generated from defaultProfile.xml UILabel + localization.ts
 * 4.7 game data - 506 entries
 */

import type { GameplayMode } from '../types/unified';

// ============================================================================
// Action Name Translations (auto-generated from game data)
// ============================================================================

export const SC_ACTION_NAMES: Record<string, string> = {
  'ammoRepool': 'Repool Ammunition',
  'attack1': 'Firearm - Attack',
  'attackSecondary': 'Tool - Secondary Fire',
  'consume': 'Firearm - Attack',
  'crouch': 'Crouch',
  'customize': 'Customize Weapon',
  'cycle_chat_lobby': 'Cycle Chat Lobby',
  'dismiss_corpse_marker': 'Dismiss Corpse Marker',
  'downedRevivalRequest': 'Request Rescue (while Incapacitated)',
  'drop': 'Drop Item',
  'emote_agree': 'Agree',
  'emote_angry': 'Angry',
  'emote_atease': 'At Ease',
  'emote_attention': 'Attention',
  'emote_blah': 'Blah',
  'emote_bored': 'Bored',
  'emote_bow': 'Bow',
  'emote_burp': 'Burp',
  'emote_cheer': 'Cheer',
  'emote_chicken': 'Chicken',
  'emote_clap': 'Clap',
  'emote_come': 'Come',
  'emote_cry': 'Cry',
  'emote_cs_forward': 'Forward',
  'emote_cs_left': 'Left',
  'emote_cs_no': 'No',
  'emote_cs_right': 'Right',
  'emote_cs_stop': 'Stop',
  'emote_cs_yes': 'Yes',
  'emote_dance': 'Dance',
  'emote_disagree': 'Disagree',
  'emote_failure': 'Failure',
  'emote_flex': 'Flex',
  'emote_flirt': 'Flirt',
  'emote_gasp': 'Gasp',
  'emote_gloat': 'Gloat',
  'emote_greet': 'Greet',
  'emote_laugh': 'Laugh',
  'emote_launch': 'Confirm Launch',
  'emote_point': 'Point',
  'emote_rude': 'Rude',
  'emote_salute': 'Salute',
  'emote_sit': 'Sit',
  'emote_sleep': 'Sleep',
  'emote_smell': 'Smell',
  'emote_taunt': 'Taunt',
  'emote_threaten': 'Threaten',
  'emote_wait': 'Wait',
  'emote_wave': 'Wave',
  'emote_whistle': 'Whistle',
  'eva_boost': 'Boost',
  'eva_brake': 'Brake',
  'eva_roll': 'Roll Left/Right',
  'eva_roll_left': 'Roll Left',
  'eva_roll_right': 'Roll Right',
  'eva_strafe_back': 'Strafe Backward',
  'eva_strafe_down': 'Strafe Down',
  'eva_strafe_forward': 'Strafe Forward',
  'eva_strafe_lateral': 'Strafe Left/Right',
  'eva_strafe_left': 'Strafe Left',
  'eva_strafe_longitudinal': 'Strafe Forward/Backward',
  'eva_strafe_right': 'Strafe Right',
  'eva_strafe_up': 'Strafe Up',
  'eva_strafe_vertical': 'Strafe Up/Down',
  'eva_toggle_headlook_mode': 'Freelook (Hold)',
  'eva_view_pitch': 'View Up/Down',
  'eva_view_pitch_down': 'View Down',
  'eva_view_pitch_mouse': 'View Up/Down',
  'eva_view_pitch_up': 'View Up',
  'eva_view_yaw': 'View Left/Right',
  'eva_view_yaw_left': 'View Left',
  'eva_view_yaw_mouse': 'View Left/Right',
  'eva_view_yaw_right': 'View Right',
  'fixed_speed_decrement': 'Default Movement Speed Decrease',
  'fixed_speed_increment': 'Default Movement Speed Increase',
  'focus_on_chat_textinput': 'Chat Window Focus',
  'foip_cyclechannel': 'Cycle through audio channels',
  'foip_pushtotalk': 'VOIP Push To Talk',
  'foip_pushtotalk_proximity': 'VOIP Push To Talk (Proximity only)',
  'foip_recalibrate': 'FOIP Recalibrate',
  'foip_viewownplayer': 'FOIP Selfie Cam',
  'force_respawn': 'Force Re-spawn (E.V.A. / On Foot)',
  'free_thirdperson_camera': 'Free View Camera (Hold)',
  'gp_crouch': 'Crouch',
  'gp_jump': 'Jump',
  'gp_movex': 'Move Left / Right',
  'gp_movey': 'Move Forward / Backward',
  'gp_rotatepitch': 'Look (Pitch)',
  'gp_rotateyaw': 'Look (Yaw)',
  'headtrack_camera_enabled': 'Enable / Disable Head Tracking for 3rd Person Camera (Toggle)',
  'headtrack_enabled': 'Enable Head Tracking (Toggle)',
  'headtrack_hold': 'Head Tracking (Hold)',
  'headtrack_recenter_device': 'Recenter Head Tracking Device (except TrackIR)',
  'holster': 'Holster Weapon',
  'incapacitatedRespawn': 'Regen (while Incapacitated)',
  'inspect': 'Inspect Item',
  'interact_with_scope': 'Interact With Scope (ADS)',
  'jump': 'Jump',
  'jump_hold': 'Jump Thrusters - Activate (hold)',
  'jump_release': 'Jump Thrusters - Release',
  'leanleft': 'Lean Left',
  'leanright': 'Lean Right',
  'ledgegrab': 'Climb Ledges',
  'melee_AttackHeavyLeft': 'Melee - Attack Heavy Left (Hold)',
  'melee_AttackHeavyRight': 'Melee - Attack Heavy Right (Hold)',
  'melee_AttackLightLeft': 'Melee - Attack Light Left',
  'melee_AttackLightRight': 'Melee - Attack Light Right',
  'melee_AttackSyringeStab': 'Medical Pen - Inject Other',
  'melee_block': 'Melee - Block (Hold)',
  'melee_dodgeBack': 'Dodge Back',
  'melee_dodgeLeft': 'Dodge left',
  'melee_dodgeRight': 'Dodge Right',
  'mobiglas': 'mobiGlas (Toggle)',
  'moveback': 'Move Backwards',
  'moveforward': 'Move Forward',
  'moveleft': 'Move Left',
  'moveright': 'Move Right',
  'nextweapon': 'Next Weapon',
  'notification_accept': 'Notifications - Accept Prompt',
  'notification_decline': 'Notifications - Decline Prompt',
  'pc_camera_orbit': 'Inventory Orbit Camera Mode',
  'pc_focus': 'Focus',
  'pc_interaction_mode': 'Interaction Mode',
  'pc_interaction_select': 'Activate Inner Thought',
  'pc_personal_thought': 'Personal Inner Thought (PIT)',
  'pc_pit_item_drop': 'Drop Item',
  'pc_pit_looting_toggle_view': 'Toggle Looting View',
  'pc_pit_looting_toggle_weapon_attachments': 'Looting - Toggle Weapon Attachments',
  'pc_qs_consumables': 'Consumable Select Radial Menu',
  'pc_screen_focus_down': 'MFD Down',
  'pc_screen_focus_left': 'MFD Left',
  'pc_screen_focus_right': 'MFD Right',
  'pc_screen_focus_up': 'MFD Up',
  'pc_select': 'Activate Inner Thought',
  'pl_exit': 'Exit seat',
  'pl_hud_open_scoreboard': 'Scoreboard',
  'port_modification_select': 'Port Modification Interact',
  'prevweapon': 'Previous Weapon',
  'prone': 'Prone',
  'prone_rollleft': 'Roll Left (while Prone)',
  'prone_rollright': 'Roll Right (while Prone)',
  'reload': 'Reload',
  'reloadSecondary': 'Reload Secondary Fire',
  'respawn': 'Re-spawn',
  'selectUnarmedCombat': 'Unarmed Combat',
  'select_gadget_pit': 'Select Gadget',
  'select_meleeweapon_pit': 'Select Melee',
  'select_primary_pit': 'Select Primary Weapon',
  'select_secondary_pit': 'Select Secondary Weapon',
  'select_sidearm_pit': 'Select Sidearm',
  'spectate_gen_nextmode': 'Spectator Camera Mode (Next)',
  'spectate_gen_prevmode': 'Spectator Camera Mode (Previous)',
  'spectate_next_target': 'Spectator Camera Target (Next)',
  'spectate_prev_target': 'Spectator Camera Target (Previous)',
  'spectate_rotatepitch': 'Spectator Camera Rotate Pitch',
  'spectate_rotatepitch_mouse': 'Spectator Camera Rotate Pitch',
  'spectate_rotateyaw': 'Spectator Camera Rotate Yaw',
  'spectate_rotateyaw_mouse': 'Spectator Camera Rotate Yaw',
  'spectate_toggle_hud': 'Spectator Camera HUD (Toggle)',
  'spectate_toggle_lock_target': 'Spectator Camera Lock Target',
  'spectate_zoom': 'Spectator Camera Zoom',
  'spectate_zoom_in': 'Spectator Camera Zoom In',
  'spectate_zoom_out': 'Spectator Camera Zoom Out',
  'sprint': 'Sprint',
  'stabilize': 'Hold Breath (ADS)',
  'takedown_nonLethal': 'Melee - Attack (Ranged Weapon + Takedowns)',
  'thirdperson': 'Third Person View (Toggle)',
  'throw_overhand': 'Throw - Overarm & Two-Handed',
  'throw_underhand': 'Throw - Underarm',
  'toggleAttachHelmet': 'Helmet\\n(Equip)',
  'toggleHelmetState': 'Default Movement Speed Increase',
  'toggle_chat': 'Chat Window (Toggle)',
  'toggle_contact': 'CommLink App (Toggle)',
  'toggle_flashlight': 'Flashlight (Toggle)',
  'toggle_lowered': 'Weapon Stance (Toggle)',
  'tractor_beam_decrease_distance': 'Tractor Beam - Decrease Distance',
  'tractor_beam_increase_distance': 'Tractor Beam - Increase Distance',
  'tractor_beam_vehicle_decrease_distance': 'Tractor Beam Vehicle - Decrease Distance',
  'tractor_beam_vehicle_increase_distance': 'Tractor Beam Vehicle- Increase Distance',
  'turret_esp_toggle': 'Turret E.S.P. Toggle On / Off',
  'turret_gyromode': 'Turret Gyro Stabilization (Toggle)',
  'turret_limiter_abs': 'Turret - Speed Limiter (abs)',
  'turret_limiter_rel': 'Turret - Speed Limiter (rel)',
  'turret_limiter_rel_decrease': 'Turret - Speed Limiter - Decrease (rel)',
  'turret_limiter_rel_increase': 'Turret - Speed Limiter - Increase (rel)',
  'turret_limiter_toggle': 'Turret - Speed Limiter - On/Off (Hold/Toggle)',
  'turret_pitch': 'Pitch',
  'turret_pitch_down': 'Pitch down',
  'turret_pitch_mouse': 'Pitch',
  'turret_pitch_up': 'Pitch up',
  'turret_recenter': 'Recenter Turret (Hold)',
  'turret_remote_exit': 'Exit Remote Turret',
  'turret_toggle_mouse_mode': 'Toggle Turret Mouse Movement (VJoy, FPS style)',
  'turret_yaw': 'Yaw',
  'turret_yaw_left': 'Yaw left',
  'turret_yaw_mouse': 'Yaw',
  'turret_yaw_right': 'Yaw right',
  'ui_notification_accept': 'Accept Invite',
  'ui_notification_decline': 'Reject Invite',
  'ui_notification_ignore': 'Ignore Invite (hold)',
  'v_afterburner': 'Boost',
  'v_atc_loading_area_request': 'Request Cargo Loading',
  'v_atc_request': 'Request Landing',
  'v_autoland': 'Autoland',
  'v_brake': 'Brake',
  'v_close_all_doors': 'Close All Doors',
  'v_cooler_throttle_down': 'Decrease Cooler Rate',
  'v_cooler_throttle_up': 'Increase Cooler Rate',
  'v_dec_scan_focus_level': 'Decrease Scanning Angle',
  'v_decrease_mining_throttle': 'Decrease Mining Laser Power',
  'v_deploy_landing_system': 'Landing System (Deploy)',
  'v_eject': 'Eject',
  'v_emergency_exit': 'Emergency Exit Seat',
  'v_flightready': 'Flight / Systems Ready',
  'v_horn': 'Horn',
  'v_hud_open_scoreboard': 'Scoreboard',
  'v_ifcs_toggle_esp': 'E.S.P. - Toggle On / Off (Press)',
  'v_ifcs_toggle_gforce_safety': 'G-Force Safety On/Off (Toggle / Hold)',
  'v_inc_scan_focus_level': 'Increase Scanning Angle',
  'v_increase_mining_throttle': 'Increase Mining Laser Power',
  'v_invoke_ping': 'Activate Ping (Hold & Release)',
  'v_jettison_volatile_cargo': 'Jettison Cargo',
  'v_lights': 'Headlights (Toggle)',
  'v_lights_off': 'Headlights\\n(Enable)',
  'v_lights_on': 'Headlights\\n(Enable)',
  'v_lock_all_doors': 'Lock All Doors',
  'v_lock_rotation': 'Lock Pitch / Yaw Movement (Toggle / Hold)',
  'v_look_ahead_enable': 'Enable / Disable Look Ahead',
  'v_look_ahead_start_target_tracking': 'Enable / Disable Target Padlock (Toggle, Hold)',
  'v_mfd_interact_cycle_backwards_long': 'MFD - Cycle Page - Backwards (Long Press)',
  'v_mfd_interact_cycle_backwards_short': 'MFD - Cycle Page - Backwards (Short Press)',
  'v_mfd_interact_cycle_forwards_long': 'MFD - Cycle Page - Forwards (Long Press)',
  'v_mfd_interact_cycle_forwards_short': 'MFD - Cycle Page - Forwards (Short Press)',
  'v_mfd_movement_down_long': 'MFD - Movement - Down (Long Press)',
  'v_mfd_movement_down_short': 'MFD - Movement - Down (Short Press)',
  'v_mfd_movement_left_long': 'MFD - Movement - Left (Long Press)',
  'v_mfd_movement_left_short': 'MFD - Movement - Left (Short Press)',
  'v_mfd_movement_right_long': 'MFD - Movement - Right (Long Press)',
  'v_mfd_movement_right_short': 'MFD - Movement - Right (Short Press)',
  'v_mfd_movement_up_long': 'MFD - Movement - Up (Long Press)',
  'v_mfd_movement_up_short': 'MFD - Movement - Up (Short Press)',
  'v_mfd_quick_action_repair_all': 'MFD - Quick Action - Self Repair All',
  'v_mfd_select_view_comms_long': 'MFD - Set Page - Communications (Long Press)',
  'v_mfd_select_view_comms_short': 'MFD - Set Page - Communications (Short Press)',
  'v_mfd_select_view_configuration_long': 'MFD - Set Page - Vehicle Configuration (Long Press)',
  'v_mfd_select_view_configuration_short': 'MFD - Set Page - Vehicle Configuration (Short Press)',
  'v_mfd_select_view_diagnostics_long': 'MFD - Set Page - Diagnostics (Long Press)',
  'v_mfd_select_view_diagnostics_short': 'MFD - Set Page - Diagnostics (Short Press)',
  'v_mfd_select_view_ifcs_long': 'MFD - Set Page - IFCS (Long Press)',
  'v_mfd_select_view_ifcs_short': 'MFD - Set Page - IFCS (Short Press)',
  'v_mfd_select_view_resource_network_long': 'MFD - Set Page - Resource Network (Long Press)',
  'v_mfd_select_view_resource_network_short': 'MFD - Set Page - Resource Network (Short Press)',
  'v_mfd_select_view_scanning_long': 'MFD - Set Page - Scanning (Long Press)',
  'v_mfd_select_view_scanning_short': 'MFD - Set Page - Scanning (Short Press)',
  'v_mfd_select_view_self_status_long': 'MFD - Set Page - Self Status (Long Press)',
  'v_mfd_select_view_self_status_short': 'MFD - Set Page - Self Status (Short Press)',
  'v_mfd_select_view_target_status_long': 'MFD - Set Page - Target Status (Long Press)',
  'v_mfd_select_view_target_status_short': 'MFD - Set Page - Target Status (Short Press)',
  'v_mfd_soft_select_cast_left_long': 'MFD - Select - Left Cast (Long Press)',
  'v_mfd_soft_select_cast_left_short': 'MFD - Select - Left Cast (Short Press)',
  'v_mfd_soft_select_cast_right_long': 'MFD - Select - Right Cast (Long Press)',
  'v_mfd_soft_select_cast_right_short': 'MFD - Select - Right Cast (Short Press)',
  'v_mfd_soft_select_mfd_10_long': 'MFD - Select - MDF 10 (Long Press)',
  'v_mfd_soft_select_mfd_10_short': 'MFD - Select - MFD 10 (Short Press)',
  'v_mfd_soft_select_mfd_1_long': 'MFD - Select - MFD 1 (Long Press)',
  'v_mfd_soft_select_mfd_1_short': 'MFD - Select - MFD 1 (Short Press)',
  'v_mfd_soft_select_mfd_2_long': 'MFD - Select - MFD 2 (Long Press)',
  'v_mfd_soft_select_mfd_2_short': 'MFD - Select - MFD 2 (Short Press)',
  'v_mfd_soft_select_mfd_3_long': 'MFD - Select - MFD 3 (Long Press)',
  'v_mfd_soft_select_mfd_3_short': 'MFD - Select - MFD 3 (Short Press)',
  'v_mfd_soft_select_mfd_4_long': 'MFD - Select - MFD 4 (Long Press)',
  'v_mfd_soft_select_mfd_4_short': 'MFD - Select - MFD 4 (Short Press)',
  'v_mfd_soft_select_mfd_5_long': 'MFD - Select - MFD 5 (Long Press)',
  'v_mfd_soft_select_mfd_5_short': 'MFD - Select - MFD 5 (Short Press)',
  'v_mfd_soft_select_mfd_6_long': 'MFD - Select - MFD 6 (Long Press)',
  'v_mfd_soft_select_mfd_6_short': 'MFD - Select - MFD 6 (Short Press)',
  'v_mfd_soft_select_mfd_7_long': 'MFD - Select - MFD 7 (Long Press)',
  'v_mfd_soft_select_mfd_7_short': 'MFD - Select - MFD 7 (Short Press)',
  'v_mfd_soft_select_mfd_8_long': 'MFD - Select - MFD 8 (Long Press)',
  'v_mfd_soft_select_mfd_8_short': 'MFD - Select - MFD 8 (Short Press)',
  'v_mfd_soft_select_mfd_9_long': 'MFD - Select - MFD 9 (Long Press)',
  'v_mfd_soft_select_mfd_9_short': 'MFD - Select - MFD 9 (Short Press)',
  'v_mfd_soft_select_mfd_primary_long': 'MFD - Select - Primary (Long Press)',
  'v_mfd_soft_select_mfd_primary_short': 'MFD - Select - Primary (Short Press)',
  'v_mgv_switch_brake_on_idle': 'Toggle Auto Braking On Idle',
  'v_mining_throttle': 'Increase / Decrease Mining Laser Power',
  'v_mining_use_consumable1': 'Activate Mining Module (Slot 1)',
  'v_mining_use_consumable2': 'Activate Mining Module (Slot 2)',
  'v_mining_use_consumable3': 'Activate Mining Module (Slot 3)',
  'v_mining_use_permanent_modifier': 'Toggle Laser Beam (High / low)',
  'v_move': 'Drive Forward / Backward',
  'v_move_back': 'Drive Backward',
  'v_move_forward': 'Drive Forward',
  'v_open_all_doors': 'Open All Doors',
  'v_pitch': 'Pitch',
  'v_pitch_down': 'Ground Vehicles - Pitch Down',
  'v_pitch_mouse': 'Pitch',
  'v_pitch_up': 'Ground Vehicles - Pitch Up',
  'v_power_set_off': 'Set Power Off',
  'v_power_set_on': 'Set Power On',
  'v_power_set_shields_off': 'Set Shields Power Off',
  'v_power_set_shields_on': 'Set Shields Power On',
  'v_power_set_thrusters_off': 'Set Thrusters Power Off',
  'v_power_set_thrusters_on': 'Set Thrusters Power On',
  'v_power_set_weapons_off': 'Set Weapons Power Off',
  'v_power_set_weapons_on': 'Set Weapons Power On',
  'v_power_throttle_down': 'Decrease Throttle',
  'v_power_throttle_max': 'Increase Throttle to Max',
  'v_power_throttle_min': 'Decrease Throttle to Min',
  'v_power_throttle_up': 'Increase Throttle',
  'v_power_toggle': 'Toggle Power - All',
  'v_power_toggle_shields': 'Toggle Power - Shields',
  'v_power_toggle_thrusters': 'Toggle Power - Thrusters',
  'v_power_toggle_weapons': 'Toggle Power - Weapons',
  'v_retract_landing_system': 'Landing System (Retract)',
  'v_roll': 'Roll',
  'v_roll_left': 'Roll left',
  'v_roll_mouse': 'Roll',
  'v_roll_right': 'Roll right',
  'v_salvage_beam_spacing_abs': 'Absolute Beam Spacing',
  'v_salvage_beam_spacing_rel': 'Relative Beam Spacing',
  'v_salvage_cycle_modifiers_focused': 'Cycle Focused Salvage Modifiers',
  'v_salvage_cycle_modifiers_left': 'Cycle Left Salvage Modifiers',
  'v_salvage_cycle_modifiers_right': 'Cycle Right Salvage Modifiers',
  'v_salvage_cycle_modifiers_structural': 'Cycle Structural Salvage Modes',
  'v_salvage_decrease_beam_spacing': 'Decrease Beam Spacing',
  'v_salvage_focus_all_heads': 'Focus all salvage heads',
  'v_salvage_focus_disintegrate': 'Focus Disintegration tool',
  'v_salvage_focus_fracture': 'Focus Fracture tool',
  'v_salvage_focus_left': 'Focus left salvage head',
  'v_salvage_focus_right': 'Focus right salvage head',
  'v_salvage_increase_beam_spacing': 'Increase Beam Spacing',
  'v_salvage_nudge_down__left': 'Nudge left salvage tool down',
  'v_salvage_nudge_down__right': 'Nudge right salvage tool down',
  'v_salvage_nudge_left__left': 'Nudge left salvage tool left',
  'v_salvage_nudge_left__right': 'Nudge right salvage tool left',
  'v_salvage_nudge_right__left': 'Nudge left salvage tool right',
  'v_salvage_nudge_right__right': 'Nudge right salvage tool right',
  'v_salvage_nudge_up__left': 'Nudge left salvage tool up',
  'v_salvage_nudge_up__right': 'Nudge right salvage tool up',
  'v_salvage_reset_gimbal': 'Salvage Mode Gimbal Reset',
  'v_salvage_toggle_beam_spacing_axis': 'Salvage Beam Axis (Toggle)',
  'v_salvage_toggle_fire_disintegrate': 'Toggle Fire Disintegrate',
  'v_salvage_toggle_fire_focused': 'Toggle Fire Focused',
  'v_salvage_toggle_fire_fracture': 'Toggle Fire Fracture',
  'v_salvage_toggle_fire_left': 'Toggle Fire Left',
  'v_salvage_toggle_fire_right': 'Toggle Fire Right',
  'v_salvage_toggle_gimbal_mode': 'Salvage Mode Gimbal (Toggle)',
  'v_scanning_trigger_scan': 'Activate Scanning',
  'v_self_destruct': 'Self Destruct',
  'v_shield_raise_level_back': 'Shield raise level back',
  'v_shield_raise_level_down': 'Shield raise level bottom',
  'v_shield_raise_level_forward': 'Shield raise level front',
  'v_shield_raise_level_left': 'Shield raise level left',
  'v_shield_raise_level_right': 'Shield raise level right',
  'v_shield_raise_level_up': 'Shield raise level top',
  'v_shield_reset_level': 'Shield reset levels',
  'v_space_brake': 'Spacebrake',
  'v_starmap': 'Map',
  'v_strafe_down': 'Strafe down (abs.)',
  'v_strafe_lateral': 'Strafe left / right (abs.)',
  'v_strafe_left': 'Strafe left (abs.)',
  'v_strafe_longitudinal_invert': 'Throttle - Forward / Back Invert',
  'v_strafe_right': 'Strafe right (abs.)',
  'v_strafe_up': 'Strafe up (abs.)',
  'v_strafe_vertical': 'Strafe up / down (abs.)',
  'v_target_cycle_all_back': 'Cycle Lock - All - Back',
  'v_target_cycle_all_fwd': 'Cycle Lock - All - Forward',
  'v_target_cycle_all_reset': 'Cycle Lock - All - Reset to Closest',
  'v_target_cycle_attacker_back': 'Cycle Lock - Attackers - Back',
  'v_target_cycle_attacker_fwd': 'Cycle Lock - Attackers - Forward',
  'v_target_cycle_attacker_reset': 'Cycle Lock - Attackers - Reset to Closest',
  'v_target_cycle_friendly_back': 'Cycle Lock - Friendlies - Back',
  'v_target_cycle_friendly_fwd': 'Cycle Lock - Friendlies - Forward',
  'v_target_cycle_friendly_reset': 'Cycle Lock - Friendlies - Reset to Closest',
  'v_target_cycle_hostile_back': 'Cycle Lock - Hostiles - Back',
  'v_target_cycle_hostile_fwd': 'Cycle Lock - Hostiles - Forward',
  'v_target_cycle_hostile_reset': 'Cycle Lock - Hostiles - Reset to Closest',
  'v_target_cycle_in_view_back': 'Cycle Lock - In View - Back',
  'v_target_cycle_in_view_fwd': 'Cycle Lock - In View - Forward',
  'v_target_cycle_in_view_reset': 'Cycle Lock - In View - Under Reticle',
  'v_target_cycle_pinned_back': 'Cycle Lock - Pinned - Back',
  'v_target_cycle_pinned_fwd': 'Cycle Lock - Pinned - Forward',
  'v_target_cycle_pinned_reset': 'Cycle Lock - Pinned - Reset to First',
  'v_target_cycle_subitem_back': 'Cycle Lock - Sub-Target - Back',
  'v_target_cycle_subitem_fwd': 'Cycle Lock - Sub-Target - Forward',
  'v_target_cycle_subitem_reset': 'Cycle Lock - Sub-Target - Reset to Main Target',
  'v_target_hail': 'Hail Target',
  'v_target_lock_selected': 'Lock Selected Target',
  'v_target_pin_selected': 'Pin Selected Target',
  'v_target_pin_selected_hold': 'Pin Selected Target (Hold)',
  'v_target_remove_all_pins': 'Remove All Pinned Targets',
  'v_target_toggle_lock_index_1': 'Pin Index 1 - Lock / Unlock Pinned Target',
  'v_target_toggle_lock_index_2': 'Pin Index 2 - Lock / Unlock Pinned Target',
  'v_target_toggle_lock_index_3': 'Pin Index 3 - Lock / Unlock Pinned Target',
  'v_target_toggle_pin_index_1': 'Pin Index 1 - Pin / Unpin Selected Target',
  'v_target_toggle_pin_index_1_hold': 'Pin Index 1 - Pin / Unpin Selected Target (Hold)',
  'v_target_toggle_pin_index_2': 'Pin Index 2 - Pin / Unpin Selected Target',
  'v_target_toggle_pin_index_2_hold': 'Pin Index 2 - Pin / Unpin Selected Target (Hold)',
  'v_target_toggle_pin_index_3': 'Pin Index 3 - Pin / Unpin Selected Target',
  'v_target_toggle_pin_index_3_hold': 'Pin Index 3 - Pin / Unpin Selected Target (Hold)',
  'v_target_tracking_auto_zoom': 'Auto Zoom On Selected Target On / Off (Toggle, Hold)',
  'v_target_unpin_selected': 'Unpin Selected Target',
  'v_target_unpin_selected_hold': 'Unpin Selected Target (Hold)',
  'v_toggle_all_doorlocks': 'Lock/Unlock Doors (Toggle)',
  'v_toggle_all_doors': 'Open/Close Doors (Toggle)',
  'v_toggle_jump_request': 'Jump Drive - Request Jump',
  'v_toggle_landing_system': 'Landing System (Toggle)',
  'v_toggle_mining_laser_fire': 'Fire Mining Laser (Toggle)',
  'v_toggle_mining_laser_type': 'Switch Mining Laser (Toggle)',
  'v_toggle_mining_mode': 'Toggle Mining Operator Mode',
  'v_toggle_missile_mode': 'Toggle Missile Operator Mode',
  'v_toggle_quantum_mode': 'Toggle Quantum Operator Mode',
  'v_toggle_relative_mouse_mode': 'Cycle mouse mode (VJoy / Relative)',
  'v_toggle_salvage_mode': 'Toggle Salvage Operator Mode',
  'v_toggle_scan_mode': 'Toggle Scanning Operator Mode',
  'v_toggle_yaw_roll_swap': 'Swap Yaw / Roll (Toggle)',
  'v_unlock_all_doors': 'Unlock All Doors',
  'v_view_cycle_fwd': 'Cycle camera view',
  'v_view_dynamic_zoom_abs': 'Dynamic Zoom In and Out (abs.)',
  'v_view_dynamic_zoom_abs_toggle': 'Dynamic Zoom Toggle (abs.)',
  'v_view_dynamic_zoom_rel': 'Dynamic Zoom In and Out (rel.)',
  'v_view_dynamic_zoom_rel_in': 'Dynamic Zoom In (rel.)',
  'v_view_dynamic_zoom_rel_out': 'Dynamic Zoom Out (rel.)',
  'v_view_freelook_mode': 'Freelook (Hold)',
  'v_view_look_behind': 'Look behind',
  'v_view_mode': 'Cycle camera orbit mode',
  'v_view_pitch': 'Look up / down',
  'v_view_pitch_down': 'Look down',
  'v_view_pitch_mouse': 'Look up / down',
  'v_view_pitch_up': 'Look up',
  'v_view_yaw': 'Look left / right',
  'v_view_yaw_left': 'Look left',
  'v_view_yaw_mouse': 'Look left / right',
  'v_view_yaw_right': 'Look right',
  'v_view_zoom_in': 'Zoom in (3rd person view)',
  'v_view_zoom_out': 'Zoom out (3rd person view)',
  'v_weapon_bombing_hud_range_decrease': 'Bombs - Decrease HUD Range',
  'v_weapon_bombing_hud_range_increase': 'Bombs - Increase HUD Range',
  'v_weapon_bombing_hud_range_reset': 'Bombs - Reset HUD Range',
  'v_weapon_bombing_toggle_desired_impact_point': 'Bombs - Toggle Desired Impact Point (Tap)',
  'v_weapon_bombing_toggle_desired_impact_point_hold': 'Bombs - Toggle Desired Impact Point (Hold)',
  'v_weapon_countermeasure_decoy_burst_decrease': 'Decoy - Decrease Burst Size (tap)',
  'v_weapon_countermeasure_decoy_burst_increase': 'Decoy - Increase Burst Size (tap)',
  'v_weapon_countermeasure_decoy_launch': 'Decoy - Launch Burst (tap), Set and Launch Burst (hold)',
  'v_weapon_countermeasure_decoy_launch_panic': 'Decoy - Panic Launch (tap)',
  'v_weapon_countermeasure_noise_launch': 'Noise - Deploy (Tap)',
  'v_weapon_cycle_missile_back': 'Cycle Previous Missile Type',
  'v_weapon_cycle_missile_fwd': 'Cycle Next Missile Type',
  'v_weapon_decrease_max_missiles': 'Decrease Number of Armed Missiles',
  'v_weapon_increase_max_missiles': 'Increase Number of Armed Missiles',
  'v_weapon_launch_missile': 'Launch Missiles (Hold)',
  'v_weapon_launch_missile_cinematic': 'Enable Cinematic Camera (Toggle)',
  'v_weapon_launch_missile_cinematic_hold': 'Enable Cinematic Camera (Hold)',
  'v_weapon_reset_max_missiles': 'Reset Number of Armed Missiles',
  'v_weapon_toggle_launch_missile': 'Launch Missiles (Tap)',
  'v_yaw': 'Yaw',
  'v_yaw_left': 'Turn Left',
  'v_yaw_mouse': 'Yaw',
  'v_yaw_right': 'Turn Right',
  'view_enable_camview_mode': 'Advanced Camera Controls Modifier (Hold)',
  'view_fov_in': 'Increase FoV',
  'view_fov_out': 'Decrease FoV',
  'view_fstop_in': 'Increase DoF',
  'view_fstop_out': 'Decrease DoF',
  'view_load_view_1': 'Load View 1',
  'view_load_view_2': 'Load View 2',
  'view_load_view_3': 'Load View 3',
  'view_load_view_4': 'Load View 4',
  'view_load_view_5': 'Load View 5',
  'view_load_view_6': 'Load View 6',
  'view_load_view_7': 'Load View 7',
  'view_load_view_8': 'Load View 8',
  'view_load_view_9': 'Load View 9',
  'view_move_target_X_neg': 'X Offset Negative',
  'view_move_target_X_pos': 'X Offset Positive',
  'view_move_target_Y_neg': 'Y Offset Negative / Spectator Freecam Focal Point Backward',
  'view_move_target_Y_pos': 'Y Offset Positive / Spectator Freecam Focal Point Forward',
  'view_move_target_Z_neg': 'Z Offset Negative',
  'view_move_target_Z_pos': 'Z Offset Positive',
  'view_reset_saved': 'Clear Saved View',
  'view_restore_defaults': 'Reset Current View',
  'view_save_view_1': 'Save View 1',
  'view_save_view_2': 'Save View 2',
  'view_save_view_3': 'Save View 3',
  'view_save_view_4': 'Save View 4',
  'view_save_view_5': 'Save View 5',
  'view_save_view_6': 'Save View 6',
  'view_save_view_7': 'Save View 7',
  'view_save_view_8': 'Save View 8',
  'view_save_view_9': 'Save View 9',
  'view_switch_to_alternative': 'Advanced Camera Controls Modifier (Hold)',
  'visor_wipe': 'Wipe Helmet Visor',
  'walk': 'Walk',
  'weapon_auxiliary_action': 'FPS Underbarrel Attachment Action',
  'weapon_change_firemode': 'Change Fire Mode',
  'weapon_melee': 'Melee - Attack (Ranged Weapon + Takedowns)',
  'weapon_zeroing_decrease': 'Weapon Zeroing Decrease',
  'weapon_zeroing_increase': 'Weapon Zeroing Increase / Auto',
  'zgt_detach': 'Detach from Surface',
  'zgt_launch': 'Launch from Surface',
  'zgt_roll_left': 'Roll Left',
  'zgt_roll_right': 'Roll Right',
  'zoom': 'Aim Down Sight',
  'zoom_in': 'Zoom In',
  'zoom_out': 'Zoom Out',
};

export const ACTION_MAP_MODES: Record<string, GameplayMode> = {
  // General
  'seat_general': 'General',
  'default': 'General',
  'player_general': 'General',
  'player_emotes': 'Social',
  'player_input_optical_tracking': 'General',

  // Spaceship
  'spaceship_general': 'Flight',
  'spaceship_view': 'Camera',
  'spaceship_movement': 'Flight',
  'spaceship_quantum': 'Flight',
  'spaceship_targeting': 'Flight',
  'spaceship_target_hailing': 'Flight',
  'spaceship_weapons': 'Flight',
  'spaceship_missiles': 'Flight',
  'spaceship_defensive': 'Flight',
  'spaceship_power': 'Flight',
  'spaceship_shields': 'Flight',
  'spaceship_radar': 'Flight',
  'spaceship_hud': 'Flight',

  // Specialized modes
  'spaceship_mining': 'Mining',
  'spaceship_salvage': 'Salvage',
  'spaceship_scanning': 'Scanning',
  'spaceship_tractor_beam': 'General',

  // Turret
  'turret_main': 'Turret',
  'turret_movement': 'Turret',
  'turret_advanced': 'Turret',

  // Vehicle
  'vehicle_general': 'Vehicle',
  'vehicle_driver': 'Vehicle',

  // FPS
  'fps_movement': 'FPS',
  'fps_view': 'FPS',
  'fps_combat': 'FPS',
  'fps_weapons': 'FPS',
  'fps_interaction': 'FPS',
  'fps_ineraction': 'FPS', // Typo in SC
  'fps_inerraction': 'FPS', // Another typo

  // EVA
  'eva_movement': 'EVA',
  'eva': 'EVA',

  // UI / Inventory
  'ui_textfield': 'General',
  'ui_notification': 'General',
  'inventory': 'Inventory',
  'zero_gravity_eva': 'EVA',
};

/**
 * Get human-readable name for a Star Citizen action
 */
export function getActionDisplayName(actionName: string): string {
  return SC_ACTION_NAMES[actionName] ?? formatActionName(actionName);
}

/**
 * Format an action name into a readable string
 * e.g., "v_toggle_mining_mode" -> "Toggle Mining Mode"
 */
export function formatActionName(actionName: string): string {
  return actionName
    // Remove prefixes
    .replace(/^v_/, '')
    .replace(/^fps_/, '')
    .replace(/^eva_/, '')
    .replace(/^vehicle_/, '')
    // Convert underscores to spaces
    .replace(/_/g, ' ')
    // Capitalize words
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Get gameplay mode for an action map name
 */
export function getGameplayMode(actionMapName: string): GameplayMode {
  return ACTION_MAP_MODES[actionMapName] ?? 'Unknown';
}
